#!/bin/zsh

RED='\033[0;31m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

title_bar='====================';

num_of_apps=7

native_dir="$HOME/Nativefier Apps"
app_suffix='-linux-x64'
app_shortcut_dir="$HOME/.local/share/applications"


app_names=(
	"Calendar"
	"Photos"
	"Notes"
	"Reminders"
	"Pages"
	"Numbers"
	"Keynote"
)

app_urls=(
	"https://www.icloud.com/calendar/"
	"https://www.icloud.com/photos/"
	"https://www.icloud.com/notes/"
	"https://www.icloud.com/reminders/"
	"https://www.icloud.com/pages/"
	"https://www.icloud.com/numbers/"
	"https://www.icloud.com/keynote/"
)

app_comments=(
	"Apple Calendar Web App"
	"Apple Photos Web App"
	"Apple Notes Web App"
	"Apple Reminders Web App"
	"Pages Web App"
	"Numbers Web App"
	"Keynote Web App"
)

# make sure every category is followed by a ';' (no spaces!)
app_categories=(
	"calendar;events;schedule"
	"photos;pictures;albums"
	"notes;lists"
	"reminders;todo"
	"pages;word;document"
	"numbers;spreadsheet;excel;tables"
	"keynote;presentation;powerpoint;slides"
)


echo -e "$CYAN$title_bar Installing Nativefier Apps $title_bar$NC"

for (( i=1; i<=$num_of_apps; i++ )) do
	name=$app_names[i]
	comment=$app_comments[i]
	categories=$app_categories[i]
	echo "$CYAN$name$NC"

	# create the electron app
	echo '   Creating nativefier app...'
	nativefier --name $app_names[i] $app_urls[i] $native_dir &> /dev/null 

	# change the app name to what we gave it above
	sed -i \
		"s/\"name\":\"\([^\"]*\)\"/\"name\":\"$app_names[i]\"/" \
		"$native_dir/$name$app_suffix/resources/app/package.json"

	# Create a desktop file so that it will show up in applications
	desktop_file="$native_dir/desktop_shortcuts/$name.desktop"
	cp 'Template.desktop' $desktop_file

	sed -i "s/<NAME>/$name/g" $desktop_file
	sed -i "s/<COMMENT>/$comment/g" $desktop_file
	sed -i "s/<CATEGORIES>/$categories/g" $desktop_file
	sed -i "s/<NATIVE_DIR>/$native_dir/g" $desktop_file

	# create a soft link to this desktop file in /home/scottedwardscoll/.local/share/applications
	echo '   Creating application shortcut...'
	ln -s "$desktop_file" "$app_shortcut_dir/$name.desktop"

	echo '   Done!'
done

echo -e "$CYAN$title_bar Installations Complete $title_bar$NC"
