#!/bin/zsh

RED='\033[0;31m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

native_dir="$HOME/Nativefier Apps"

app_folder_suffix='-linux-x64';
template_desktop='Template.desktop';
desktop_shortcut_dir='desktop_shortcuts';

app_shortcut_dir="$HOME/.local/share/applications"

title_bar='====================';

echo -e "$CYAN$title_bar Uninstalling Nativefier Apps $title_bar$NC"

app_names=($(ls "$native_dir/$desktop_shortcut_dir/" | sed 's/\.desktop//'))
num_apps=$(echo $app_names | wc -w)

for (( i=1; i<=$num_apps; i++)) do
	name=$app_names[i];
	echo -e " $CYAN$name$NC";
	echo "   Removing shortcut '$app_shortcut_dir/$name.desktop'...";
	rm "$app_shortcut_dir/$name.desktop" 2> /dev/null;
	rm "$native_dir/$desktop_shortcut_dir/$name.desktop" 2> /dev/null;
	echo "   Deleting app...";
	rm -rf "$native_dir/$name$app_folder_suffix";
	echo '   Done!';
done

echo -e 'All apps removed!';
